### ISSUE TITLE
Custom Sidebar is overriden by the plugins

### ISSUE THREAD

**Issue by flozero** [youngtailors/vuepress-plugin-component-docgen#1]
Hello ! First thank's a lot for your work ! :)

I am facing two problems:

when we are using your component it broke every sidebar we make. Maybe i should just add another nav ?

```
sidebar: {
      "/guide/": [
        {
          title: "Guide",
          collapsable: false,
          children: ["", "getting-started", "colors", "borders", "fonts", "filters"]
        },
        {
          title: "Components",
          collapsable: false,
          children: ["components/buttons", "components/modals"]
        }
      ]
    }
```

It seem to break all sidebar navigation because the Home / Components

We can't use all vue-docgen-api when i want to use slot comment emit comment and class description maybe it's a choice ?

link to the [issue](https://github.com/youngtailors/vuepress-plugin-component-docgen/issues/2)

**Comment by dacsang97** [comment]
Ref: https://github.com/youngtailors/vuepress-plugin-component-docgen/blob/master/src/build/enhancer/app.ts#L8-L29

**Comment by dacsang97** [comment]
This issue belongs to this code:
https://github.com/youngtailors/vuepress-plugin-component-docgen/blob/9e7cdea828cb86cf4cb2d2d063161c4260a9e6a2/src/build/enhancer/app.ts#L6-L32

So, can you create PR to fix this?

**Comment by dacsang97** [comment]
Because I use the sidebar to show list components, so your sidebar had broken. I think we need an individual page to show list component, instead of sidebar

**Comment by flozero** [comment]
Sure i will try to this tonight 👍

**Comment by flozero** [comment]
Did you change something ?

**Comment by dacsang97** [comment]
Sorry I'm busy with some other projects, and preparing for Tet holiday (in my country - Vietnam), so I will see it soon. It's a blessing if you can help me.

**Comment by flozero** [comment]
https://github.com/f3ltron/vuepress-plugin-component-docgen. I Am working on ^^. I added some comments on codes and add an example directory to working on. And analyze a bit your code. 

I think yeah we should create a totally new page with additionalPages ?

Actually we use enhanceAppFiles i added a new children that is work but sidebar options car be array nester array of object, objects. so yeah i dont know what is the best on it

**Comment by flozero** [comment]
Update: 
I make it working with both groups sections sidebar and basic sidebar navigation.

Need improvement:
- Messy code
- work well when one depth folder archi from components.

archi components working

```
src/
  components/
            Test.vue // making the nav but not taking the good md
             // Working Actually
            Comp/
                 Comp.vue
                 SubComp/
                      SubComp.vue
            Comp2/
                 Comp2.vue
```

maybe nest sub Component should not work

edit: It should work i think because the good practice you should create one folder by component or create one folder by theme of components

**Comment by flozero** [comment]
Pull request created: [Here](https://github.com/youngtailors/vuepress-plugin-component-docgen/pull/3)

**Comment by dacsang97** [comment]
https://github.com/youngtailors/vuepress-plugin-component-docgen/pull/3
